/** Theme engine: schema, validation, and built-in themes. */

export {
  themeSchema,
  validateTheme,
  withThemeDefaults,
  createThemeDraft,
  DEFAULT_THEME_BRANDING,
  type Theme,
  type ThemeAlignment,
  type ThemeBranding,
  type ThemeHeadingStyle,
  type ThemeTextStyle,
  type ThemeValidationResult,
} from './schema.js';
export {
  builtinThemes,
  getBuiltinTheme,
  minimalTheme,
  modernTheme,
  githubTheme,
  technicalTheme,
  corporateTheme,
  elegantTheme,
  documentationTheme,
  spectrumTheme,
  coralTheme,
  spearmintTheme,
  tropicTheme,
  plumTheme,
  geometricTheme,
  writerTheme,
  academicTheme,
  newsletterTheme,
  slateTheme,
  sunsetTheme,
  forestTheme,
  paperTheme,
  midnightTheme,
  meetingTheme,
  proposalTheme,
  officeTheme,
  facetTheme,
  ionTheme,
  organicTheme,
  retrospectTheme,
  sliceTheme,
  wispTheme,
  bandedTheme,
  dividendTheme,
  whitepaperTheme,
  resumeTheme,
  agendaTheme,
  brochureTheme,
  formalLetterTheme,
} from './builtin.js';
